version: 2.1

workflows:
  build:
    jobs:
      - build:
          name: build_lowest
          composer_args: --prefer-lowest
      - build:
          name: build_highest

jobs:
  build:
    parameters:
      composer_args:
        type: string
        default: ""
    docker:
      - image: skpr/php-circleci:7.4-1.x
    working_directory: /data
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ arch }}
      - run:
          name: "Install Dependencies"
          command: composer update --prefer-dist --no-progress --no-suggest --no-interaction <<parameters.composer_args>>
      - save_cache:
          key: deps-{{ arch }}
          paths:
            - vendor
      - run:
          name: "Lint"
          command: ./bin/phpcs
      - run:
          name: "Test"
          command: |
            mkdir -p ~/phpunit
            ./bin/phpunit --testsuite unit --log-junit ~/phpunit/phpunit.xml
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
